### ISSUE TITLE
output of table-extraction causing errors

### ISSUE THREAD

**Issue by lukehsiao** [lukehsiao/HardwareDeepDive#26] opened 2016-02-04 18:34 UTC
After working on #23, I am seeing some errors when running ```deepdive init``` using MobaXTerm sshed into my VirtualBox VM.

```
lh@lh:~/repos/HardwareDeepDive$ deepdive initdb
NOTICE:  table "part_temperature_features" does not exist, skipping
DROP TABLE
CREATE TABLE
NOTICE:  table "part_num_mentions" does not exist, skipping
DROP TABLE
CREATE TABLE
NOTICE:  table "storage_temp_mentions" does not exist, skipping
DROP TABLE
CREATE TABLE
NOTICE:  table "part_temperature" does not exist, skipping
DROP TABLE
CREATE TABLE
NOTICE:  table "part_temperature_candidates" does not exist, skipping
DROP TABLE
CREATE TABLE
NOTICE:  table "table_dump" does not exist, skipping
DROP TABLE
CREATE TABLE
NOTICE:  table "collector_current_mentions" does not exist, skipping
DROP TABLE
CREATE TABLE
NOTICE:  table "part_collector_current_candidates" does not exist, skipping
DROP TABLE
CREATE TABLE
++ dirname input/init.sh
+ cd input
+ INPUT_FILES='pdf/*'
++ wc -l
++ ls pdf/112823.pdf pdf/2N3906-D.PDF pdf/2N3906.pdf pdf/2N4123-D.PDF pdf/2N4124.pdf pdf/2N6426-D.PDF pdf/2N6427.pdf pdf/AUKCS04635-1.pdf pdf/BC182-D.PDF pdf/BC182.pdf pdf/BC337-D.PDF pdf/BC337.pdf pdf/BC546A_Series_B14-521026.pdf 'pdf/BC546-BC548C(TO-92).pdf' pdf/bc546_diotec.pdf pdf/bc546-d.pdf pdf/BC546.pdf pdf/BC547.pdf pdf/bc550.pdf pdf/BC818-40LT1-D.PDF pdf/BC818.pdf pdf/CSEMS02553-1.pdf pdf/CSEMS02742-1.pdf pdf/CSEMS03485-1.pdf pdf/CSEMS05382-1.pdf pdf/CSEMS05383-1.pdf pdf/DIODS00215-1.pdf pdf/DIODS12641-1.pdf pdf/DIODS13249-1.pdf pdf/DISES00023-1.pdf pdf/DISES00189-1.pdf pdf/DISES00192-1.pdf pdf/DISES00242-1.pdf pdf/DISES00490-1.pdf pdf/DISES00616-1.pdf pdf/DISES00645-1.pdf pdf/dtc114w.pdf pdf/FAIRS19194-1.pdf pdf/FAIRS25065-1.pdf pdf/Infineon-BC817KSERIES_BC818KSERIES-DS-v01_01-en.pdf pdf/Infineon-BC857SERIES_BC858SERIES_BC859SERIES_BC860SERIES-DS-v01_01-en.pdf pdf/INFNS19372-1.pdf pdf/JCSTS01155-1.pdf pdf/KECCS03676-1.pdf pdf/KECCS05435-1.pdf pdf/LITES00424-1.pdf pdf/LITES00686-1.pdf pdf/LITES00689-1.pdf pdf/LITES00690-1.pdf pdf/LTSCS02910-1.pdf pdf/LTSCS02912-1.pdf pdf/LTSCS02920-1.pdf pdf/MCCCS08610-1.pdf pdf/MCCCS08818-1.pdf pdf/MCCCS08984-1.pdf pdf/MCCCS09540-1.pdf pdf/MCCCS09741-1.pdf pdf/MINDS00015-1.pdf pdf/MMBT3904.pdf pdf/MMMCS17742-1.pdf pdf/MOTOS03160-1.pdf pdf/MOTOS03189-1.pdf pdf/MOTOS04676-1.pdf pdf/MOTOS04796-1.pdf pdf/ONSMS04099-1.pdf pdf/PHGLS18216-1.pdf pdf/PHGLS19500-1.pdf pdf/PHGLS20125-1.pdf pdf/PHGLS20126-1.pdf pdf/PHGLS20267-1.pdf pdf/PHGLS25601-1.pdf pdf/PJECS00521-1.pdf pdf/PNJIS00254-1.pdf pdf/PNJIS01186-1.pdf pdf/PNJIS01305-1.pdf pdf/PNJIS01453-1.pdf pdf/PNJIS01593-1.pdf pdf/RECTS00705-1.pdf pdf/RECTS01002-1.pdf pdf/RECTS01158-1.pdf pdf/RECTS01214-1.pdf pdf/RECTS01242-1.pdf pdf/RECTS01325-1.pdf pdf/SAMSD00049-518.pdf pdf/SCSCS02175-1.pdf pdf/SCSCS02324-1.pdf pdf/SGSTS13702-1.pdf pdf/SGSTS13734-1.pdf pdf/SIEMS01215-1.pdf pdf/TKCGS00622-1.pdf pdf/TWSCS04757-1.pdf pdf/UTCLS01324-1.pdf pdf/UTCLS02155-1.pdf pdf/UTCLS03593-1.pdf pdf/VISHS23888-1.pdf pdf/VSMIS00373-1.pdf pdf/VSMIS03793-1.pdf pdf/WEILS00082-1.pdf pdf/WEITS00252-1.pdf pdf/ZETXS01948-1.pdf
+ NUM_FILES=100
+ echo '[info] Total Number of Datasheets: 100'
[info] Total Number of Datasheets: 100
+ START_TIME=0
+ export -f extract_table
+ MAX_JOBS=4
+ find pdf/112823.pdf pdf/2N3906-D.PDF pdf/2N3906.pdf pdf/2N4123-D.PDF pdf/2N4124.pdf pdf/2N6426-D.PDF pdf/2N6427.pdf pdf/AUKCS04635-1.pdf pdf/BC182-D.PDF pdf/BC182.pdf pdf/BC337-D.PDF pdf/BC337.pdf pdf/BC546A_Series_B14-521026.pdf 'pdf/BC546-BC548C(TO-92).pdf' pdf/bc546_diotec.pdf pdf/bc546-d.pdf pdf/BC546.pdf pdf/BC547.pdf pdf/bc550.pdf pdf/BC818-40LT1-D.PDF pdf/BC818.pdf pdf/CSEMS02553-1.pdf pdf/CSEMS02742-1.pdf pdf/CSEMS03485-1.pdf pdf/CSEMS05382-1.pdf pdf/CSEMS05383-1.pdf pdf/DIODS00215-1.pdf pdf/DIODS12641-1.pdf pdf/DIODS13249-1.pdf pdf/DISES00023-1.pdf pdf/DISES00189-1.pdf pdf/DISES00192-1.pdf pdf/DISES00242-1.pdf pdf/DISES00490-1.pdf pdf/DISES00616-1.pdf pdf/DISES00645-1.pdf pdf/dtc114w.pdf pdf/FAIRS19194-1.pdf pdf/FAIRS25065-1.pdf pdf/Infineon-BC817KSERIES_BC818KSERIES-DS-v01_01-en.pdf pdf/Infineon-BC857SERIES_BC858SERIES_BC859SERIES_BC860SERIES-DS-v01_01-en.pdf pdf/INFNS19372-1.pdf pdf/JCSTS01155-1.pdf pdf/KECCS03676-1.pdf pdf/KECCS05435-1.pdf pdf/LITES00424-1.pdf pdf/LITES00686-1.pd+ xargs -n 1 -P 4 -I '{}' bash -c 'extract_table "$1" ' _ '{}'
f pdf/LITES00689-1.pdf pdf/LITES00690-1.pdf pdf/LTSCS02910-1.pdf pdf/LTSCS02912-1.pdf pdf/LTSCS02920-1.pdf pdf/MCCCS08610-1.pdf pdf/MCCCS08818-1.pdf pdf/MCCCS08984-1.pdf pdf/MCCCS09540-1.pdf pdf/MCCCS09741-1.pdf pdf/MINDS00015-1.pdf pdf/MMBT3904.pdf pdf/MMMCS17742-1.pdf pdf/MOTOS03160-1.pdf pdf/MOTOS03189-1.pdf pdf/MOTOS04676-1.pdf pdf/MOTOS04796-1.pdf pdf/ONSMS04099-1.pdf pdf/PHGLS18216-1.pdf pdf/PHGLS19500-1.pdf pdf/PHGLS20125-1.pdf pdf/PHGLS20126-1.pdf pdf/PHGLS20267-1.pdf pdf/PHGLS25601-1.pdf pdf/PJECS00521-1.pdf pdf/PNJIS00254-1.pdf pdf/PNJIS01186-1.pdf pdf/PNJIS01305-1.pdf pdf/PNJIS01453-1.pdf pdf/PNJIS01593-1.pdf pdf/RECTS00705-1.pdf pdf/RECTS01002-1.pdf pdf/RECTS01158-1.pdf pdf/RECTS01214-1.pdf pdf/RECTS01242-1.pdf pdf/RECTS01325-1.pdf pdf/SAMSD00049-518.pdf pdf/SCSCS02175-1.pdf pdf/SCSCS02324-1.pdf pdf/SGSTS13702-1.pdf pdf/SGSTS13734-1.pdf pdf/SIEMS01215-1.pdf pdf/TKCGS00622-1.pdf pdf/TWSCS04757-1.pdf pdf/UTCLS01324-1.pdf pdf/UTCLS02155-1.pdf pdf/UTCLS03593-1.pdf pdf/VISHS23888-1.pdf pdf/VSMIS00373-1.pdf pdf/VSMIS03793-1.pdf pdf/WEILS00082-1.pdf pdf/WEITS00252-1.pdf pdf/ZETXS01948-1.pdf -maxdepth 1 -iname '*.pdf'
[info] Loading pdf/112823.pdf...
[info] Loading pdf/2N3906.pdf...
[info] Loading pdf/2N4123-D.PDF...
[info] Loading pdf/2N3906-D.PDF...
[info] Loading pdf/2N4124.pdf...
[info] Loading pdf/2N6426-D.PDF...
[info] Loading pdf/2N6427.pdf...
[info] Loading pdf/AUKCS04635-1.pdf...
[info] Loading pdf/BC182-D.PDF...
[info] Loading pdf/BC182.pdf...
[info] Loading pdf/BC337-D.PDF...
[info] Loading pdf/BC337.pdf...
[info] Loading pdf/BC546A_Series_B14-521026.pdf...
[info] Loading pdf/BC546-BC548C(TO-92).pdf...
[info] Loading pdf/bc546_diotec.pdf...
[info] Loading pdf/bc546-d.pdf...
[info] Loading pdf/BC546.pdf...
ERROR:  extra data after last expected column
CONTEXT:  COPY table_dump, line 18: "BC546-BC548C(TO-92).pdf    0       0       row     3       BC546-BC548C(TO-92).pdf 0       0       row     4       TM      3"
xtermxterm[info] Loading pdf/BC547.pdf...
[info] Loading pdf/bc550.pdf...
[info] Loading pdf/BC818-40LT1-D.PDF...
[info] Loading pdf/BC818.pdf...
[info] Loading pdf/CSEMS02553-1.pdf...
[info] Loading pdf/CSEMS02742-1.pdf...
[info] Loading pdf/CSEMS03485-1.pdf...
[info] Loading pdf/CSEMS05382-1.pdf...
[info] Loading pdf/CSEMS05383-1.pdf...
[info] Loading pdf/DIODS00215-1.pdf...
[info] Loading pdf/DIODS12641-1.pdf...
[info] Loading pdf/DIODS13249-1.pdf...
[info] Loading pdf/DISES00023-1.pdf...
[info] Loading pdf/DISES00189-1.pdf...
[info] Loading pdf/DISES00192-1.pdf...
[info] Loading pdf/DISES00242-1.pdf...
[info] Loading pdf/DISES00490-1.pdf...
[info] Loading pdf/DISES00616-1.pdf...
[info] Loading pdf/DISES00645-1.pdf...
[info] Loading pdf/dtc114w.pdf...
[info] Loading pdf/FAIRS19194-1.pdf...
[info] Loading pdf/FAIRS25065-1.pdf...
[info] Loading pdf/Infineon-BC817KSERIES_BC818KSERIES-DS-v01_01-en.pdf...
[info] Loading pdf/Infineon-BC857SERIES_BC858SERIES_BC859SERIES_BC860SERIES-DS-v01_01-en.pdf...
[info] Loading pdf/INFNS19372-1.pdf...
[info] Loading pdf/JCSTS01155-1.pdf...
[info] Loading pdf/KECCS03676-1.pdf...
[info] Loading pdf/KECCS05435-1.pdf...
[info] Loading pdf/LITES00424-1.pdf...
[info] Loading pdf/LITES00686-1.pdf...
[info] Loading pdf/LITES00689-1.pdf...
[info] Loading pdf/LITES00690-1.pdf...
[info] Loading pdf/LTSCS02910-1.pdf...
[info] Loading pdf/LTSCS02912-1.pdf...
[info] Loading pdf/LTSCS02920-1.pdf...
[info] Loading pdf/MCCCS08610-1.pdf...
[info] Loading pdf/MCCCS08818-1.pdf...
[info] Loading pdf/MCCCS08984-1.pdf...
[info] Loading pdf/MCCCS09540-1.pdf...
ERROR:  extra data after last expected column
CONTEXT:  COPY table_dump, line 2: "MCCCS08818-1.pdf    0       0       header  1       MCCCS08818-1.pdf        0       0       header  2       20736 Marilla Street Chats..."
xtermxterm[info] Loading pdf/MCCCS09741-1.pdf...
ERROR:  extra data after last expected column
CONTEXT:  COPY table_dump, line 11: "MCCCS08984-1.pdf   0       0       row     1       MCCCS08984-1.pdf        0       0       row     2       MMBT3904        8"
xtermxterm[info] Loading pdf/MINDS00015-1.pdf...
ERROR:  extra data after last expected column
CONTEXT:  COPY table_dump, line 22: "MCCCS08610-1.pdf   0       0       row     2       MCCCS08610-1.pdf        0       0       row     3       TM      1"
xtermxterm[info] Loading pdf/MMBT3904.pdf...
[info] Loading pdf/MMMCS17742-1.pdf...
ERROR:  extra data after last expected column
CONTEXT:  COPY table_dump, line 2: "MMMCS17742-1.pdf    0       0       header  1       xtermxtermMMMCS17742-1.pdf      0       0       header  2       20736 Marilla Street Chats..."
[info] Loading pdf/MOTOS03160-1.pdf...
ERROR:  extra data after last expected column
CONTEXT:  COPY table_dump, line 4: "MCCCS09540-1.pdf    0       0       row     3       MCCCS09540-1.pdf        0       0       row     4       TM      81"
xtermxterm[info] Loading pdf/MOTOS03189-1.pdf...
ERROR:  extra data after last expected column
CONTEXT:  COPY table_dump, line 2: "MCCCS09741-1.pdf    0       0       header  1       MCCCS09741-1.pdf        0       0       header  2       20736 Marilla Street Chats..."
xtermxterm[info] Loading pdf/MOTOS04676-1.pdf...
[info] Loading pdf/MOTOS04796-1.pdf...
[info] Loading pdf/ONSMS04099-1.pdf...
[info] Loading pdf/PHGLS18216-1.pdf...
[info] Loading pdf/PHGLS19500-1.pdf...
[info] Loading pdf/PHGLS20125-1.pdf...
[info] Loading pdf/PHGLS20126-1.pdf...
[info] Loading pdf/PHGLS20267-1.pdf...
[info] Loading pdf/PHGLS25601-1.pdf...
[info] Loading pdf/PJECS00521-1.pdf...
[info] Loading pdf/PNJIS00254-1.pdf...
[info] Loading pdf/PNJIS01186-1.pdf...
[info] Loading pdf/PNJIS01305-1.pdf...
[info] Loading pdf/PNJIS01453-1.pdf...
[info] Loading pdf/PNJIS01593-1.pdf...
[info] Loading pdf/RECTS00705-1.pdf...
[info] Loading pdf/RECTS01002-1.pdf...
[info] Loading pdf/RECTS01158-1.pdf...
[info] Loading pdf/RECTS01214-1.pdf...
[info] Loading pdf/RECTS01242-1.pdf...
[info] Loading pdf/RECTS01325-1.pdf...
[info] Loading pdf/SAMSD00049-518.pdf...
[info] Loading pdf/SCSCS02175-1.pdf...
[info] Loading pdf/SCSCS02324-1.pdf...
[info] Loading pdf/SGSTS13702-1.pdf...
[info] Loading pdf/SGSTS13734-1.pdf...
[info] Loading pdf/SIEMS01215-1.pdf...
[info] Loading pdf/TKCGS00622-1.pdf...
[info] Loading pdf/TWSCS04757-1.pdf...
[info] Loading pdf/UTCLS01324-1.pdf...
[info] Loading pdf/UTCLS02155-1.pdf...
[info] Loading pdf/VISHS23888-1.pdf...
[info] Loading pdf/UTCLS03593-1.pdf...
[info] Loading pdf/VSMIS00373-1.pdf...
[info] Loading pdf/VSMIS03793-1.pdf...
[info] Loading pdf/WEILS00082-1.pdf...
[info] Loading pdf/WEITS00252-1.pdf...
[info] Loading pdf/ZETXS01948-1.pdf...
lh@lh:~/repos/HardwareDeepDive$ xtermxtermxtermxtermxtermxtermxtermxtermxtermxtermxtermxtermxtermxterm
```

It seems like the string xterm is being randomly output, which is causing some errors.

**Comment by lukehsiao** [comment] 2016-02-04 18:57
The output of table-extraction on ```BC546-BC548C(TO-92).pdf``` contains strange xterm's like this:
```
BC546-BC548C(TO-92).pdf 0       0       row     2       BC547A/B/C      70
BC546-BC548C(TO-92).pdf 0       0       row     3       omponents       4
BC546-BC548C(TO-92).pdf 0       0       row     4       TM      3
BC546-BC548C(TO-92).pdf 0       0       row     5       20736 Marilla Street Chatsworth 5
BC546-BC548C(TO-92).pdf 0       0       row     6       Micro Commercial Components     1
BC546-BC548C(TO-92).pdf 0       0       row     7               6
BC546-BC548C(TO-92).pdf 0       0       row     7       BC548A/B/C      71
BC546-BC548C(TO-92).pdf 0       0       row     8
        7
BC546-BC548C(TO-92).pdf 0       0       row     9          xtermxterm
        8
BC546-BC548C(TO-92).pdf 0       0       row     10      Features        2
BC546-BC548C(TO-92).pdf 0       0       row     11      NPN Silicon     72
BC546-BC548C(TO-92).pdf 0       0       row     12       Through Hole Package   9
BC546-BC548C(TO-92).pdf 0       0       row     13      Amplifier Transistor    73
BC546-BC548C(TO-92).pdf 0       0       row     14       150oC Junction Temperature     10
BC546-BC548C(TO-92).pdf 0       0       row     15      (cid:120) Case Material: Molded Plastic. ULFlammability 11
BC546-BC548C(TO-92).pdf 0       0       row     16      625mW   74
BC546-BC548C(TO-92).pdf 0       0       row     17      Classification Rating 94V-0 and MSL rating 1    12
BC546-BC548C(TO-92).pdf 0       0       row     18      (cid:120)  Marking:Type Number  13
BC546-BC548C(TO-92).pdf 0       0       row     19      •   Lead Free Finish/Rohs Compliant) ("P"Suffix designates      14
BC546-BC548C(TO-92).pdf 0       0       rowxterm        20      Compliant.  See ordering information)   15
BC546-BC548C(TO-92).pdf 0       0       row     21      TO-92   75
BC546-BC548C(TO-92).pdf 0       0       row     22      Mechanical Data 16
BC546-BC548C(TO-92).pdf 0       0       row     23      A       76
```

**Comment by lukehsiao** [comment] 2016-02-04 19:07
@xiao-cheng 

```
BC546-BC548C(TO-92).pdf 0       0       row     7               6
BC546-BC548C(TO-92).pdf 0       0       row     7       BC548A/B/C      71
BC546-BC548C(TO-92).pdf 0       0       row     8
        7
BC546-BC548C(TO-92).pdf 0       0       row     9
        8
BC546-BC548C(TO-92).pdf 0       0       row     10      Features        2
```

I believe the code that is actually outputting this is:
```python
    if out_dir is None:
        for relation in relations:
            print base_pdf + '\t' + page_num + '\t' + table_id + '\t' + relation.tab_delim_str()
    else:
        out_file = uid + '.tsv'
        out_file = os.path.join(out_dir,out_file)
        if verbose:
            print 'Writing relations to', out_file
        with codecs.open(out_file,'w','utf-8') as f:
            for relation in relations:
                f.write('\t' + base_pdf + '\t' + page_num + '\t' + table_id + '\t' + relation.tab_delim_str() + '\n')       
```
in parse.py. Is it possible that relation.tab_delim_str() has a bug in it's contents? I noticed in the output above that there is sometimes no mention text (just spaces?) or perhaps in the case of row 8 or row 9, the mention_text contains a newline?

If I run this directly in linux (not using xterm), I do not get the random "xterm" strings, and that same line of code I show above displays like this:

![image](https://cloud.githubusercontent.com/assets/7573542/12826329/5aff52c6-cb2f-11e5-9309-d2443ebe4712.png)

Any idea what those symbols are?

**Comment by lukehsiao** [comment] 2016-02-04 19:51
@hchiang: Do you also get errors like below when you run it deepdive initdb?

```
ERROR:  extra data after last expected column
CONTEXT:  COPY table_dump, line 2: "MCCCS08818-1.pdf    0       0       header  1       MCCCS08818-1.pdf        0       0       header  2       20736 Marilla Street Chats..."
```

**Comment by xiao-cheng** [comment] 2016-02-04 22:27
I think it's just an encoding problem. I'll strip out all non-printable
unicode for now.

**Comment by xiao-cheng** [comment] 2016-02-05 00:20
do a pull and it should be fixed

**Comment by lukehsiao** [comment] 2016-02-05 00:29
Getting these errors:
```
[info] Loading pdf/BC182.pdf...
  File "../udf/table-extraction/parse.py", line 167, in <module>
    process_pdf(args.filename, out_dir = args.output)
  File "../udf/table-extraction/parse.py", line 62, in process_pdf
    mentions, relations = parse_layout(layout, scaler)
  File "/home/lh/repos/HardwareDeepDive/udf/table-extraction/pdf/pdf_parsers.py", line 75, in parse_layout
    relations.append(Relation('header', hid, m.keep_allowed_chars, i))
AttributeError: 'LTTextLineHorizontal' object has no attribute 'keep_allowed_chars'
```

**Comment by xiao-cheng** [comment] 2016-02-05 00:41
Sorry about it! The auto refactoring changed some unrelated attributes.
Just commited a fix and please pull again.

**Comment by lukehsiao** [comment] 2016-02-05 00:49
Looks like that resolved it. No errors on any of the 100 PDFs when running ```deepdive initdb```.

Thanks Xiao!

**Comment by lukehsiao** [comment] 2016-02-26 19:20
@xiao-cheng: With DeepDive v0.8.0, I'm getting this error again:

```
lh@dd:~/repos/HardwareDeepDive$ deepdive redo table_dump
‘data/table_dump.done’ -> ‘data/table_dump.done~’
‘process/init/relation/table_dump.done’ -> ‘process/init/relation/table_dump.done~’
‘run/RUNNING’ -> ‘20160226/111455.615277172’
‘run/LATEST’ -> ‘20160226/111455.615277172’
2016-02-26 11:14:57.454018 # on dd: deepdive do table_dump
2016-02-26 11:14:57.455888 # run/20160226/111455.615277172/plan.sh
2016-02-26 11:14:57.458826 # execution plan for data/table_dump
2016-02-26 11:14:57.459586
2016-02-26 11:14:57.460026 : ## process/init/app ##########################################################
2016-02-26 11:14:57.460399 : # Done: 2016-02-26T11:09:36-0800 (5m 19s ago)
2016-02-26 11:14:57.460834 : process/init/app/run.sh
2016-02-26 11:14:57.461207 : mark_done process/init/app
2016-02-26 11:14:57.461538 : ##############################################################################
2016-02-26 11:14:57.461801
2016-02-26 11:14:57.461916
2016-02-26 11:14:57.462428 ## process/init/relation/table_dump ##########################################
2016-02-26 11:14:57.462609 # Done: 2016-02-26T11:14:26-0800 (29s ago)
2016-02-26 11:14:57.462848 process/init/relation/table_dump/run.sh
2016-02-26 11:14:57.463016 ++ dirname process/init/relation/table_dump/run.sh
2016-02-26 11:14:57.463161 + cd process/init/relation/table_dump
2016-02-26 11:14:57.463305 + export DEEPDIVE_CURRENT_PROCESS_NAME=process/init/relation/table_dump
2016-02-26 11:14:57.463446 + DEEPDIVE_CURRENT_PROCESS_NAME=process/init/relation/table_dump
2016-02-26 11:14:57.463582 + deepdive create table table_dump
2016-02-26 11:14:57.618567 CREATE TABLE
2016-02-26 11:14:57.620396 + deepdive load table_dump
2016-02-26 11:14:57.700599 Loading table_dump from input/table_dump.tsv.sh (tsv format)
loading table_dump: 0:03:31 12.1MiB [58.5KiB/s] ([58.5KiB/s])
loading table_dump: 0:03:31  256k [1.21k/s] ([1.21k/s])2016-02-26 11:18:29.303008 input/table_dump.tsv.sh: line 24: create_tables.sql: command not found
2016-02-26 11:18:29.307651 ERROR:  extra data after last expected column
2016-02-26 11:18:29.307728 CONTEXT:  COPY table_dump, line 82: "AUKCS04635-1.pdf        0       0       center_col      02N4124.pdf     0       0       header  0       2N4124  /  MMBT4124     0"
‘run/ABORTED’ -> ‘20160226/111455.615277172’
lh@dd:~/repos/HardwareDeepDive$
```

Any ideas?

**Comment by lukehsiao** [comment] 2016-02-26 19:31
Ok, I still have that error:

```
2016-02-26 11:27:42.842342 + deepdive load table_dump
loading table_dump: 0:00:01    0 B [   0 B/s] ([   0 B/s])able_dump.tsv.sh (tsv format)
loading table_dump: 0:03:13  256k [1.32k/s] ([1.32k/s])
loading table_dump: 0:03:13 12.1MiB [63.9KiB/s] ([63.9KiB/s])
2016-02-26 11:30:56.817277 ERROR:  extra data after last expected column
2016-02-26 11:30:56.817356 CONTEXT:  COPY table_dump, line 82: "AUKCS04635-1.pdf        0       0       center_col      02N4124.pdf     0       0       header  0       2N4124  /  MMBT4124     0"
‘run/ABORTED’ -> ‘20160226/112740.198465802’
lh@dd:~/repos/HardwareDeepDive$
```

**Comment by xiao-cheng** [comment] 2016-02-26 19:42
is it because multiple processes are printing overlapping lines?

**Comment by lukehsiao** [comment] 2016-02-26 19:43
Perhaps? It happens late into the run (3mins in). It works for just one file fine.

**Comment by xiao-cheng** [comment] 2016-02-26 19:46
xargs have no guarantee on interleaved output, we should switch the GNU parallel in this case

**Comment by lukehsiao** [comment] 2016-02-26 19:48
I wonder why this didn't happen with DeepDive 0.7.1 then.

**Comment by xiao-cheng** [comment] 2016-02-26 21:18
concurrency is hard to write and debug.. might be something not related to 0.8 at all

**Comment by xiao-cheng** [comment] 2016-02-26 21:30
OK i think I'll add multiprocessing to the python code instead of bash, since starting a python VM and imports takes a lot of unnecessary time and resources for each file. and it is much easier write things in python. the commandline would just be
`
python parse.py folder/
`
and it will walk through all pdfs underneath

**Comment by xiao-cheng** [comment] 2016-02-26 22:25
Alright, just updated the code, give it a try.
Also I changed the db.url to require environment variable PGPORT to be set to the postgres port, which is 5432 by default. I had to have this for running multiple databases on the server and is generally a good idea.

**Comment by lukehsiao** [comment] 2016-02-26 22:27
Awesome! I will just it a try soon and let you know how it goes.

**Comment by lukehsiao** [comment] 2016-02-26 23:33
So, now my table_dump.tsv.sh should just be something like:
```
#!/usr/bin/env bash
# A script for loading DeepDive data into PostgreSQL database
set -euo pipefail
cd "$(dirname "$0")"

INPUT_FILES=pdf/
python ../udf/table-extraction/parse.py $INPUT_FILES
```

correct?

**Comment by xiao-cheng** [comment] 2016-02-26 23:34
Yes. Also in your .bashrc file add
`
export PGPORT=5432
`

**Comment by lukehsiao** [comment] 2016-02-26 23:38
With the export, it's still giving me invalid port number:

```
2016-02-26 15:37:36.701465 ## process/init/relation/table_dump ##########################################
2016-02-26 15:37:36.702015 # Done: 2016-02-26T15:32:34-0800 (5m 1s ago)
2016-02-26 15:37:36.702587 process/init/relation/table_dump/run.sh
2016-02-26 15:37:36.703122 ++ dirname process/init/relation/table_dump/run.sh
2016-02-26 15:37:36.703527 + cd process/init/relation/table_dump
2016-02-26 15:37:36.704208 + export DEEPDIVE_CURRENT_PROCESS_NAME=process/init/relation/table_dump
2016-02-26 15:37:36.705055 + DEEPDIVE_CURRENT_PROCESS_NAME=process/init/relation/table_dump
2016-02-26 15:37:36.705646 + deepdive create table table_dump
2016-02-26 15:37:36.793590 psql: invalid port number: "#PGPORT"
‘run/ABORTED’ -> ‘20160226/153735.136371213’
lh@dd:~/repos/HardwareDeepDive$ $PGPORT
5432
lh@dd:~/repos/HardwareDeepDive$
```

**Comment by xiao-cheng** [comment] 2016-02-26 23:47
Oops, it should be $PGPORT instead of #PGPORT in db.url, can you change it and try again?

**Comment by lukehsiao** [comment] 2016-02-26 23:56
The change on *$*PGPORT worked. However, after 3mins, I got this error:

```
2016-02-26 15:53:22.584703 ## process/init/relation/table_dump ##########################################
2016-02-26 15:53:22.584889 # Done: 2016-02-26T15:44:42-0800 (8m 39s ago)
2016-02-26 15:53:22.585086 process/init/relation/table_dump/run.sh
2016-02-26 15:53:22.585257 ++ dirname process/init/relation/table_dump/run.sh
2016-02-26 15:53:22.585427 + cd process/init/relation/table_dump
2016-02-26 15:53:22.585588 + export DEEPDIVE_CURRENT_PROCESS_NAME=process/init/relation/table_dump
2016-02-26 15:53:22.585851 + DEEPDIVE_CURRENT_PROCESS_NAME=process/init/relation/table_dump
2016-02-26 15:53:22.586134 + deepdive create table table_dump
2016-02-26 15:53:22.705814 CREATE TABLE
2016-02-26 15:53:22.707729 + deepdive load table_dump
loading table_dump: 0:00:01    0  [   0 /s] ([   0 /s])t/table_dump.tsv.sh (tsv format)
loading table_dump: 0:02:58 12.1MiB [69.5KiB/s] ([69.5KiB/s])
loading table_dump: 0:02:58  256k [1.44k/s] ([1.44k/s])
2016-02-26 15:56:20.922757 ERROR:  extra data after last expected column
2016-02-26 15:56:20.922864 CONTEXT:  COPY table_dump, line 516: "2N6426-D.PDF   0       0       2N3906-D.PDF    0       0       header  0       2N3906  0"
‘run/ABORTED’ -> ‘20160226/155320.991080837’
```

Also, does parse.py still work for individual files? Or does it need to be given a directory now?

**Comment by xiao-cheng** [comment] 2016-02-27 00:08
Yes on individual file it works the same. Can you commit to dev or a separate branch so I can pull and investigate?

**Comment by lukehsiao** [comment] 2016-02-27 00:09
Yes, just pushed to `general-ext`.

**Comment by xiao-cheng** [comment] 2016-02-27 00:24
can you push db.url and all changes under input/ as well? It seems to not create any tables for me

**Comment by lukehsiao** [comment] 2016-02-27 00:25
Those changes are there. I was running:

```
deepdive compile
deepdive do table_dump
```

**Comment by xiao-cheng** [comment] 2016-02-27 00:38
ok
` 
export PYTHONIOENCODING=utf-8 and try again
`

**Comment by xiao-cheng** [comment] 2016-02-27 00:43
you can just try on the 112823.pdf file and see if there are weird characters in rows (unicode encoded in ascii)

**Comment by lukehsiao** [comment] 2016-02-27 00:44
```
2016-02-26 16:39:31.553617 ## process/init/relation/table_dump ##########################################
2016-02-26 16:39:31.553714 # Done: 2016-02-26T15:57:22-0800 (42m 7s ago)
2016-02-26 16:39:31.553810 process/init/relation/table_dump/run.sh
2016-02-26 16:39:31.553905 ++ dirname process/init/relation/table_dump/run.sh
2016-02-26 16:39:31.554008 + cd process/init/relation/table_dump
2016-02-26 16:39:31.554106 + export DEEPDIVE_CURRENT_PROCESS_NAME=process/init/relation/table_dump
2016-02-26 16:39:31.554295 + DEEPDIVE_CURRENT_PROCESS_NAME=process/init/relation/table_dump
2016-02-26 16:39:31.554454 + deepdive create table table_dump
2016-02-26 16:39:31.688361 CREATE TABLE
2016-02-26 16:39:31.690028 + deepdive load table_dump
2016-02-26 16:39:31.765001 Loading table_dump from input/table_dump.tsv.sh (tsv format)
loading table_dump: 0:03:29 12.1MiB [59.2KiB/s] ([59.2KiB/s])
loading table_dump: 0:03:29  256k [1.22k/s] ([1.22k/s])
2016-02-26 16:43:00.949244 ERROR:  extra data after last expected column
2016-02-26 16:43:00.949325 CONTEXT:  COPY table_dump, line 516: "2N6426-D.PDF   0       0       2N3906-D.PDF    0       0       header  0       2N3906  0"
‘run/ABORTED’ -> ‘20160226/163929.376062364’
lh@dd:~/repos/HardwareDeepDive$ $PYTHONIOENCODING
utf-8
```

If i just run on 112823.pdf it works fine.

**Comment by lukehsiao** [comment] 2016-02-27 00:49
I also seem to get an error when I just try to fun it on 2N64260D.pdf
```
python ../udf/table-extraction/parse.py pdf/2N6426-D.pdf
```

Results in 
```
2016-02-26 16:46:49.287301 Loading table_dump from input/table_dump.tsv.sh (tsv format)
2016-02-26 16:46:49.289453 ++ dirname input/table_dump.tsv.sh
2016-02-26 16:46:49.290626 + cd input
2016-02-26 16:46:49.290683 + INPUT_FILES=pdf/
2016-02-26 16:46:49.290698 + python ../udf/table-extraction/parse.py pdf/2N6426-D.pdf
2016-02-26 16:46:49.522475 usage: parse.py [-h] [-d] [-f] [-o OUTPUT] [-p PROCESS] [--version] FILE
loading table_dump: 0:00:00    0 B [   0 B/s] ([   0 B/s])N6426-D.pdf does not exist!
loading table_dump: 0:00:00    0  [   0 /s] ([   0 /s])
2016-02-26 16:46:49.545541 COPY 0
2016-02-26 16:46:49.550668 mark_done process/init/relation/table_dump
2016-02-26 16:46:49.559508 ##############################################################################
2016-02-26 16:46:49.559625
2016-02-26 16:46:49.559657
2016-02-26 16:46:49.559726 ## data/table_dump ###########################################################
2016-02-26 16:46:49.559778 # Done: 2016-02-26T16:46:06-0800 (41s ago)
2016-02-26 16:46:49.559797 # no-op
2016-02-26 16:46:49.559814 mark_done data/table_dump
2016-02-26 16:46:49.569993 ##############################################################################
2016-02-26 16:46:49.570061
2016-02-26 16:46:49.570076
‘run/FINISHED’ -> ‘run/FINISHED~’
```

Where table_dump is just empty.

**Comment by xiao-cheng** [comment] 2016-02-27 00:55
The single file case worked for me. I'm trying to see why concurrency breaks the output when running on all 100

**Comment by xiao-cheng** [comment] 2016-02-27 01:00
It seems that the python process lock I was using for print is not working. Trying to find a way to make it work

**Comment by xiao-cheng** [comment] 2016-02-28 04:40
Alright, it should be fixed.
The root cause is `sys.stdout` not flushing after `print` statements, thus even though inter-process locking was done correctly, each process's buffer was not flushed to stdout even after locks are released, causing overlapping lines

**Comment by lukehsiao** [comment] 2016-02-28 04:40
Wow, nice find. Thanks Xiao!

**Closed by xiao-cheng** 2016-02-28 04:40 UTC
Labels: bug, in progress
